<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://impl.service.demo.example.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://service.demo.example.com/" name="HelloServiceImplService" targetNamespace="http://impl.service.demo.example.com/">
  <wsdl:import location="http://localhost:8081/soap/helloService?wsdl=HelloService.wsdl" namespace="http://service.demo.example.com/">
    </wsdl:import>
  <wsdl:binding name="HelloServiceImplServiceSoapBinding" type="ns1:HelloService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sayHello">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="sayHello">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="sayHelloResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="HelloServiceImplService">
    <wsdl:port binding="tns:HelloServiceImplServiceSoapBinding" name="HelloServiceImplPort">
      <soap:address location="http://localhost:8081/soap/helloService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>